# Generated by Django 5.0.3 on 2024-03-07 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_rename_email_user_email_rename_name_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed', models.CharField(max_length=100)),
                ('published_at', models.DateTimeField(verbose_name='published date')),
            ],
        ),
    ]
