# Generated by Django 5.0.3 on 2024-03-07 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_feedmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedmodel',
            name='published_at',
        ),
    ]
